#!/usr/bin/env bash

set -eo pipefail

if [ -z "${_OUTPUT_LINE_BUFFERED:-}" ]; then
  export _OUTPUT_LINE_BUFFERED=true
  if command -v stdbuf >/dev/null; then exec stdbuf -oL -eL "$0" "$@"; fi
fi

export GIT_ROOT=${GIT_ROOT:-"${PWD:-"$(pwd)"}"}
export OUTPUT_DIR="$GIT_ROOT/output"

source "$GIT_ROOT/Xfile_source/impl.sh"

link_child_xfile "$GIT_ROOT/Xfile_source/tests/tests.sh" '' test_xfile

# ---------- Xfile development ----------

function bash_version { ## log bash version (which runs Xfile)
  puts "$BASH_VERSION"
}

function reset_git_hooks { ## Unset local core.hooksPath (clears examples/ios demo hooks)
  local current
  current=$(git config --local --get core.hooksPath || echo '<not specified in config>')
  log_info "core.hooksPath git config state:" \
    "- In local config:" "$current"

  if git config --local --unset-all core.hooksPath 2>/dev/null; then
    log_success "Removed local core.hooksPath"
  else
    log_note "hooksPath is already absent from local config"
  fi
}

function release_bump_ref_in_setup {
  assert_semver "$1"

  log_next "Will change version in:" Xfile_source/setup.sh Xfile_source/impl.sh README.md

  sed -i '' "s/{XFILE_REF:-.*}/{XFILE_REF:-$1}/1" ./Xfile_source/setup.sh
  sed -i '' "s#XFILE_REF=\${2:-.*}#XFILE_REF=\${2:-$1}#1" ./Xfile_source/impl.sh
  sed -i '' "s/XFILE_REF='.*'/XFILE_REF='$1'/1" ./README.md
}

function release_zip_source_dir {
  log_next "Will zip ./Xfile_source to $OUTPUT_DIR/Xfile_source.zip"

  mkdir -p "$OUTPUT_DIR"
  zip -r "$OUTPUT_DIR/Xfile_source.zip" ./Xfile_source
}

function assert_semver {
  if [[ ! "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    log_error "Bad semver: $1"
    return 9
  fi
}

begin_xfile_task
